import type { CatalogComponent } from './types'

// Coordinates for hotspots match the procedural models in src/three/models.tsx:
// bodies sit around y = 0…1.5, legs point down to y ≈ −1.

export const CATALOG: CatalogComponent[] = [
  {
    id: 'battery',
    name: 'Battery',
    technical: 'Battery (9 V, 6LR61)',
    group: 'power',
    symbol: 'battery',
    unlockLevel: 1,
    what: 'A small box of chemicals that creates a steady push of electricity.',
    does: 'It keeps a fixed voltage between its + and − terminals, pushing current round any loop connected to them.',
    why: 'Without a source of push, nothing in a circuit moves. Every robot needs a power source.',
    where: ['Smoke alarms', 'Remote controls', 'Every mobile robot (usually a rechargeable pack)'],
    analogy: { text: 'A water pump that keeps the pressure up.', limit: 'A pump moves water from one place to another. A battery moves electrons round a loop, and they all come back.' },
    hotspots: [
      { id: 'pos', label: '+ terminal', detail: 'The small round snap. Conventional current flows out of here.', position: [-0.25, 1.95, 0] },
      { id: 'neg', label: '− terminal', detail: 'The larger hexagonal snap. Current returns here. We usually call this point ground (0 V).', position: [0.25, 1.95, 0] },
      { id: 'body', label: 'Six cells inside', detail: 'A 9 V battery is really six tiny 1.5 V cells connected in series: 6 × 1.5 = 9 V.', position: [0.52, 0.9, 0.32] },
    ],
    tryIt: { label: 'Stack cells in the battery lesson', to: '/lesson/batteries' },
  },
  {
    id: 'resistor',
    name: 'Resistor',
    technical: 'Resistor (through-hole, ¼ W)',
    group: 'passive',
    symbol: 'resistor',
    unlockLevel: 2,
    what: 'A small part that makes it harder for electricity to flow.',
    does: 'It limits how much current flows. Higher resistance (more ohms) means less current.',
    why: 'Lots of parts, LEDs especially, would draw too much current and destroy themselves. A resistor sets a safe amount.',
    where: ['Next to almost every LED', 'Setting signal levels for microcontrollers', 'Sensor circuits'],
    analogy: { text: 'A narrow section in a pipe.', limit: 'A narrow pipe doesn’t heat up, but a resistor turns the energy it blocks into heat.' },
    hotspots: [
      { id: 'bands', label: 'Colour bands', detail: 'The stripes encode its value. Yellow-violet-brown means 4, 7, plus one zero = 470 Ω.', position: [-0.3, 0.7, 0.25] },
      { id: 'body', label: 'Body', detail: 'Inside is a thin film of carbon or metal. Making the film longer or thinner increases the resistance.', position: [0.2, 0.7, 0.3] },
      { id: 'leads', label: 'Legs', detail: 'A resistor has no direction, so you can plug it in either way round.', position: [1.15, -0.5, 0] },
    ],
    tryIt: { label: 'Change resistors in Experiment 02', to: '/experiment/change-the-resistor' },
  },
  {
    id: 'led',
    name: 'LED',
    technical: 'Light-emitting diode (5 mm)',
    group: 'semiconductor',
    symbol: 'led',
    unlockLevel: 2,
    what: 'A tiny light that only lets current flow one way.',
    does: 'It glows when current flows from its long leg (+) to its short leg (−). Backwards, it stays dark.',
    why: 'Status lights, displays, and the “hello world” of electronics. It’s also a great way to see that current is flowing.',
    where: ['Power indicators', 'Screens and TVs', 'Robot status lights'],
    hotspots: [
      { id: 'anode', label: 'Long leg = + (anode)', detail: 'Connect this towards the battery’s +.', position: [-0.25, -1.15, 0] },
      { id: 'cathode', label: 'Short leg = − (cathode)', detail: 'Connect this towards the battery’s −.', position: [0.25, -0.75, 0] },
      { id: 'flat', label: 'Flat edge', detail: 'The rim is flattened on the − side. It’s handy when the legs have been cut to the same length.', position: [0.62, 0.08, 0] },
      { id: 'die', label: 'The chip (die)', detail: 'A speck of semiconductor that gives off light when current crosses it. The plastic dome works as a lens.', position: [0, 0.75, 0] },
    ],
    tryIt: { label: 'Light (and break) one in Experiment 01', to: '/experiment/light-an-led' },
  },
  {
    id: 'switch',
    name: 'Switch',
    technical: 'Toggle switch (SPST)',
    group: 'switching',
    symbol: 'switch',
    unlockLevel: 2,
    what: 'A lever that opens or closes a gap in the circuit.',
    does: 'Closed: the loop is complete and current flows. Open: there is a gap and nothing flows.',
    why: 'Turning things on and off by hand: power switches, mode selectors, safety cut-offs.',
    where: ['Robot power switches', 'Light switches', 'Torches'],
    hotspots: [
      { id: 'lever', label: 'Lever', detail: 'Flip it and a metal contact inside moves to touch, or let go of, the other contact.', position: [0.2, 1.4, 0] },
      { id: 'pins', label: 'Two pins', detail: 'SPST means single-pole single-throw: one circuit, one on/off position.', position: [0.3, -0.7, 0] },
    ],
  },
  {
    id: 'button',
    name: 'Push button',
    technical: 'Tactile switch (momentary)',
    group: 'switching',
    symbol: 'button',
    unlockLevel: 2,
    what: 'A switch that’s only on while you hold it down.',
    does: 'Pressing it closes the gap, and letting go opens it again (“momentary”).',
    why: 'It’s the simplest way for a person to give a robot an input, like Start, Reset or Mode.',
    where: ['Keyboards', 'Reset buttons', 'Microcontroller inputs'],
    hotspots: [
      { id: 'cap', label: 'Button cap', detail: 'Pushing it bends a tiny metal dome inside, which bridges the two contacts.', position: [0, 0.75, 0] },
      { id: 'legs', label: 'Four legs, two pairs', detail: 'The legs on opposite sides are permanently connected. The button connects one pair to the other.', position: [0.45, -0.4, 0.45] },
    ],
    tryIt: { label: 'Build a button-controlled LED in Experiment 03', to: '/experiment/button-led' },
  },
  {
    id: 'potentiometer',
    name: 'Potentiometer',
    technical: 'Potentiometer (10 kΩ, linear)',
    group: 'passive',
    symbol: 'potentiometer',
    unlockLevel: 4,
    what: 'A knob with a resistor inside, and a third leg that slides along it.',
    does: 'Its two outer legs are the ends of a resistor track. The middle leg (the wiper) slides along the track as you turn, picking off any voltage between the two ends.',
    why: 'It turns a position into a voltage a microcontroller can read: knobs, joysticks, and the angle sensor inside every servo.',
    where: ['Volume and brightness knobs', 'Joysticks', 'Inside servo motors'],
    analogy: { text: 'A slider on a ramp. Wherever you stop it, it reports how high up the ramp it is.', limit: 'It only works if almost no current is taken from the wiper. It’s a sensor, not a way to power things.' },
    hotspots: [
      { id: 'knob', label: 'Knob (shaft)', detail: 'Turning it slides the wiper along the track inside, about three quarters of a full turn from end to end.', position: [0, 1.3, 0] },
      { id: 'wiper', label: 'Middle leg: the wiper', detail: 'Connect this to an analog pin. Its voltage moves as the knob turns.', position: [0, -0.75, 0.3] },
      { id: 'ends', label: 'Outer legs: the track ends', detail: 'Wire one to 5V and the other to GND. Swap them and the knob just works the other way round.', position: [-0.32, -0.45, 0.3] },
      { id: 'code', label: '“103” on the body', detail: 'Its total resistance, written like a resistor’s bands: 1, 0, then 3 zeros = 10 000 Ω = 10 kΩ.', position: [0.4, 0.46, 0.56] },
    ],
    tryIt: { label: 'Read one with a microcontroller in Experiment 04', to: '/experiment/read-pot' },
  },
  {
    id: 'capacitor',
    name: 'Capacitor',
    technical: 'Electrolytic capacitor',
    group: 'passive',
    symbol: 'capacitor',
    unlockLevel: 2,
    what: 'A tiny, very fast energy storage tank.',
    does: 'It soaks up electrical charge and gives it back quickly, smoothing out sudden dips and spikes in voltage.',
    why: 'Motors and microcontrollers make the supply voltage wobble. Capacitors near them steady it so nothing resets at random.',
    where: ['Next to every chip on a board', 'Power supplies', 'Motor drivers'],
    analogy: { text: 'A small water tower that tops up the pressure when demand suddenly jumps.', limit: 'It holds very little energy compared with a battery, only enough for split-second gaps.' },
    hotspots: [
      { id: 'stripe', label: 'Minus stripe', detail: 'This type has a direction. The stripe marks the − leg, and fitting it backwards can make it fail, sometimes with a pop.', position: [0.5, 0.8, 0] },
      { id: 'vent', label: 'Safety vent', detail: 'The scored top lets gas escape safely if it’s abused, instead of bursting.', position: [0, 1.45, 0] },
      { id: 'legs', label: 'Long = +, short = −', detail: 'Same rule as an LED.', position: [-0.2, -0.9, 0] },
    ],
  },
  {
    id: 'diode',
    name: 'Diode',
    technical: 'Rectifier diode (1N4007)',
    group: 'semiconductor',
    symbol: 'diode',
    unlockLevel: 2,
    what: 'A one-way door for electricity.',
    does: 'Current can flow in the direction of the arrow on its symbol, but almost none flows the other way.',
    why: 'It protects circuits from batteries plugged in backwards, and stops motors kicking voltage back into your electronics.',
    where: ['Reverse-polarity protection', 'Across relay coils and motors', 'Converting AC to DC'],
    hotspots: [
      { id: 'band', label: 'Silver band = − side', detail: 'The band marks the cathode, the end current flows out of.', position: [0.4, 0.65, 0.25] },
      { id: 'body', label: 'Body', detail: 'Inside is a silicon junction. It needs about 0.7 V before it starts to conduct.', position: [-0.2, 0.65, 0.25] },
    ],
  },
  {
    id: 'transistor',
    name: 'Transistor',
    technical: 'Bipolar junction transistor (NPN, 2N2222)',
    group: 'semiconductor',
    symbol: 'npn',
    unlockLevel: 2,
    what: 'An electronic switch, or a valve, controlled by a tiny current.',
    does: 'A small current into its middle leg (base) lets a much bigger current flow between the other two legs.',
    why: 'A microcontroller pin can only supply a few milliamps. A transistor lets that weak signal control something bigger.',
    where: ['Driving LEDs and buzzers from a microcontroller', 'Amplifiers', 'Billions of them inside every chip'],
    hotspots: [
      { id: 'flat', label: 'Flat face', detail: 'Hold the flat face towards you to read the pin order from the datasheet, often E-B-C.', position: [0, 0.5, 0.15] },
      { id: 'base', label: 'Base (control)', detail: 'The small control current goes in here.', position: [0, -0.7, 0] },
      { id: 'ce', label: 'Collector & emitter', detail: 'The big current flows between these two.', position: [0.3, -0.7, 0] },
    ],
  },
  {
    id: 'mosfet',
    name: 'MOSFET',
    technical: 'N-channel MOSFET (TO-220)',
    group: 'semiconductor',
    symbol: 'mosfet',
    unlockLevel: 2,
    what: 'An electronic switch you can turn on and off with a small electrical signal.',
    does: 'Put voltage on its gate and a path opens between drain and source that can carry amps of current, with almost no control current needed.',
    why: 'Switching motors, lights and heaters from a microcontroller. It’s the workhorse of robot motor drivers.',
    where: ['Motor drivers', 'Drone speed controllers', 'Power supplies'],
    analogy: { text: 'A tap: a light twist on the handle (the gate) controls a big flow of water.', limit: 'A tap barely heats up. A MOSFET wastes a little power as heat, which is why it has a metal tab for a heatsink.' },
    hotspots: [
      { id: 'gate', label: 'Gate (G)', detail: 'The control leg. Voltage here, not current, opens the switch.', position: [-0.35, -0.7, 0] },
      { id: 'drain', label: 'Drain (D)', detail: 'The load (e.g. a motor) usually connects here.', position: [0, -0.7, 0] },
      { id: 'tab', label: 'Metal tab', detail: 'Bolt a heatsink here to carry away heat. It’s electrically connected to the drain.', position: [0, 1.35, -0.2] },
    ],
  },
  {
    id: 'relay',
    name: 'Relay',
    technical: 'Electromechanical relay (5 V coil)',
    group: 'switching',
    symbol: 'relay',
    unlockLevel: 2,
    what: 'A switch flipped by a small electromagnet.',
    does: 'Powering the coil makes it magnetic, which pulls a metal arm and closes a completely separate circuit. You can hear it click.',
    why: 'It lets a low-voltage circuit safely control a totally separate, even high-voltage, circuit.',
    where: ['Home automation', 'Car electronics', 'Industrial machines'],
    hotspots: [
      { id: 'coil', label: 'Coil (inside)', detail: 'A coil of thin wire. Current through it makes a magnet.', position: [-0.35, 0.95, 0.42] },
      { id: 'contacts', label: 'Switch contacts (inside)', detail: 'Pulled closed by the magnet. This side is electrically separate from the coil.', position: [0.35, 0.95, 0.42] },
    ],
  },
  {
    id: 'connector',
    name: 'Connector',
    technical: 'Screw terminal block (2-pin)',
    group: 'connection',
    symbol: 'connector',
    unlockLevel: 2,
    what: 'A way to plug or screw wires onto a board so they can be removed later.',
    does: 'Clamps a wire firmly against a metal contact that’s soldered to the board.',
    why: 'Batteries, motors and sensors need to be attached and detached. Connectors make that possible without soldering.',
    where: ['Battery inputs', 'Motor outputs on drivers', 'Every robot wiring harness'],
    hotspots: [
      { id: 'screw', label: 'Clamp screw', detail: 'Tighten it to squeeze the wire against the contact.', position: [-0.3, 0.95, 0] },
      { id: 'entry', label: 'Wire entry', detail: 'Strip about 5 mm of insulation and push the bare wire in here.', position: [-0.3, 0.4, 0.45] },
    ],
  },
  {
    id: 'fuse',
    name: 'Fuse',
    technical: 'Glass cartridge fuse',
    group: 'protection',
    symbol: 'fuse',
    unlockLevel: 2,
    what: 'A thin wire designed to melt on purpose.',
    does: 'If too much current flows, for example in a short circuit, the wire melts and breaks the loop before anything else gets damaged.',
    why: 'Robot batteries can deliver enough current to start a fire. A fuse is cheap insurance.',
    where: ['Battery packs', 'Cars', 'Power inputs on robot boards'],
    hotspots: [
      { id: 'element', label: 'Fuse wire', detail: 'Sized to melt at a chosen current, for example 2 A.', position: [0, 0.65, 0.2] },
      { id: 'caps', label: 'Metal end caps', detail: 'They clip into a fuse holder, so a blown fuse is easy to replace.', position: [0.7, 0.65, 0] },
    ],
  },
  {
    id: 'regulator',
    name: 'Voltage regulator',
    technical: 'Linear regulator (7805)',
    group: 'power',
    symbol: 'regulator',
    unlockLevel: 2,
    what: 'A part that turns a wobbly or too-high voltage into a steady one.',
    does: 'Feed it anything from about 7 V to 20 V and it outputs a steady 5 V.',
    why: 'Motors want battery voltage, but microcontrollers need exactly 5 V or 3.3 V. A regulator gives the brain a clean supply.',
    where: ['Arduino boards', 'Robot power systems', 'USB gadgets'],
    hotspots: [
      { id: 'in', label: 'Input', detail: 'Higher, unregulated voltage goes in here (e.g. 9 V battery).', position: [-0.35, -0.7, 0] },
      { id: 'gnd', label: 'Ground', detail: 'The shared 0 V reference.', position: [0, -0.7, 0] },
      { id: 'out', label: 'Output', detail: 'A steady 5 V comes out. The extra voltage is burned off as heat.', position: [0.35, -0.7, 0] },
    ],
  },
  {
    id: 'microcontroller',
    name: 'Microcontroller board',
    technical: 'Development board (Arduino Uno style, ATmega328P)',
    group: 'computing',
    symbol: 'mcu',
    unlockLevel: 5,
    what: 'A tiny computer on a chip, mounted on a board with pins you can wire to.',
    does: 'It runs one program over and over: reading its input pins, deciding what to do, and switching its output pins.',
    why: 'It’s the brain of a robot. Change the code and the same wires do something completely different.',
    where: ['Every robot', 'Washing machines and microwaves', 'Keyboards, drones and 3D printers'],
    analogy: { text: 'A very fast, very literal assistant with a checklist that it repeats forever.', limit: 'It does exactly what the code says, even when that’s a mistake, and its pins are far too weak to drive a motor directly.' },
    hotspots: [
      { id: 'chip', label: 'The microcontroller chip', detail: 'The actual computer: a processor, memory for your program, and the circuits behind every pin.', position: [0.45, -0.15, 0.05] },
      { id: 'usb', label: 'USB socket', detail: 'Loads your program from a computer, powers the board, and carries serial monitor messages back.', position: [-1.25, 0.05, 0.45] },
      { id: 'headers', label: 'Pin headers', detail: 'Push jumper wires in here: power pins (5V, GND), analog inputs (A0…) and digital pins (D0…D13).', position: [0.35, -0.1, 0.88] },
      { id: 'led', label: 'The “L” LED', detail: 'Wired to pin 13, so you can test code with no wiring at all.', position: [-0.35, -0.2, -0.3] },
      { id: 'jack', label: 'Power jack', detail: 'Lets the board run from a battery instead of a USB cable.', position: [-1.2, 0.05, -0.55] },
    ],
    tryIt: { label: 'Program one in Experiment 05', to: '/experiment/button-code' },
  },
  {
    id: 'temp-sensor',
    name: 'Temperature sensor',
    technical: 'Analog temperature sensor (TMP36)',
    group: 'sensing',
    symbol: 'sensor',
    unlockLevel: 6,
    what: 'A tiny chip that turns temperature into a voltage.',
    does: 'Its middle leg gives 0.5 V at 0 °C, plus 10 mV for every degree warmer.',
    why: 'Batteries and motors misbehave when they get hot. A robot that can feel heat can slow down before something fails.',
    where: ['Thermostats', 'Battery chargers', 'Inside laptops and phones'],
    hotspots: [
      { id: 'face', label: 'Flat face', detail: 'Hold the flat face towards you and the legs are +, OUT, − from left to right. Get + and − backwards and it gets hot fast.', position: [0, 0.5, 0.05] },
      { id: 'out', label: 'Middle leg: OUT', detail: 'The voltage that means temperature. Wire it to an analog pin.', position: [0, -0.75, 0] },
      { id: 'power', label: 'Outer legs: + and −', detail: '+ to 5V, − to GND. The sensor is a small circuit and needs power to work.', position: [-0.25, -0.45, 0] },
    ],
    tryIt: { label: 'Read one in Experiment 07', to: '/experiment/read-temp' },
  },
  {
    id: 'ultrasonic',
    name: 'Ultrasonic sensor',
    technical: 'Ultrasonic distance sensor (HC-SR04)',
    group: 'sensing',
    symbol: 'sensor',
    unlockLevel: 6,
    what: 'A distance sensor that works like a bat, with sound too high-pitched to hear.',
    does: 'It sends a short click of sound and times the echo. Distance = time × the speed of sound ÷ 2.',
    why: 'It’s the cheapest way to give a robot a sense of what’s in front of it, from 2 cm to about 4 m.',
    where: ['Obstacle-avoiding robots', 'Car parking sensors', 'Tank level gauges'],
    analogy: { text: 'Shouting in a canyon and counting how long the echo takes.', limit: 'Soft things like curtains swallow the sound, and walls at a slant bounce it away, so the sensor can miss them.' },
    hotspots: [
      { id: 'tx', label: 'Speaker (T)', detail: 'Sends a burst of 40 kHz sound, twice as high as people can hear.', position: [-0.62, 0.18, 0.5] },
      { id: 'rx', label: 'Microphone (R)', detail: 'Listens for the echo. The board times how long it took.', position: [0.62, 0.18, 0.5] },
      { id: 'pins', label: 'VCC · TRIG · ECHO · GND', detail: 'TRIG starts a measurement. ECHO goes HIGH for exactly as long as the sound took to come back.', position: [0, -0.6, 0.1] },
    ],
    tryIt: { label: 'Ping a wall in the ultrasonic lesson', to: '/lesson/ultrasonic' },
  },
  {
    id: 'servo',
    name: 'Servo',
    technical: 'Hobby servo motor (SG90-style)',
    group: 'motion',
    symbol: 'motor',
    unlockLevel: 7,
    what: 'A motor that turns to an angle you choose and holds it there.',
    does: 'A pulse every 20 ms sets the angle: 1 ms for 0°, 2 ms for 180°. Inside, a potentiometer measures the arm so the servo can correct itself.',
    why: 'Steering, grippers, robot arms and pan-and-tilt cameras all need precise angles.',
    where: ['RC car steering', 'Robot arms and grippers', 'Camera mounts'],
    hotspots: [
      { id: 'horn', label: 'Horn', detail: 'The arm that turns. Clip-on horns come in different shapes.', position: [0.4, 0.95, 0] },
      { id: 'wires', label: 'Three wires', detail: 'Brown = GND, red = + (about 5 V), orange = signal pulses.', position: [-1.3, -0.4, 0] },
      { id: 'inside', label: 'Inside the case', detail: 'A small DC motor, a gearbox and a potentiometer: a complete closed-loop system in a box.', position: [0, 0.1, 0.45] },
    ],
    tryIt: { label: 'Steer one in Experiment 08', to: '/experiment/servo' },
  },
  {
    id: 'dc-motor',
    name: 'DC gear motor',
    technical: 'Brushed DC motor with gearbox ("TT" motor, 6 V)',
    group: 'motion',
    symbol: 'motor',
    unlockLevel: 7,
    what: 'A motor that spins whenever current flows through it, with a gearbox to make it slower and stronger.',
    does: 'Its speed follows the voltage, and swapping its two wires reverses it. Held still, it draws its biggest current: the stall current.',
    why: 'It’s what turns a robot’s wheels.',
    where: ['Robot wheels', 'Toys', 'Fans and pumps'],
    analogy: { text: 'A bicycle in a low gear: the gearbox trades speed for strength.', limit: 'A motor also acts like a generator while it spins, which is why its current drops once it gets going.' },
    hotspots: [
      { id: 'can', label: 'Motor can', detail: 'Coils and magnets inside. Current through the coils makes them push against the magnets.', position: [-1.1, 0.75, 0] },
      { id: 'gearbox', label: 'Gearbox', detail: 'Slows the fast little motor down about 48 times and makes it 48 times stronger.', position: [0.1, 0.75, 0.4] },
      { id: 'terminals', label: 'Two terminals', detail: 'No + or −: whichever way round you connect it sets the direction it spins.', position: [-1.55, 0.3, 0.25] },
    ],
    tryIt: { label: 'Drive one in Experiment 09', to: '/experiment/dc-motor' },
  },
  {
    id: 'motor-driver',
    name: 'Motor driver',
    technical: 'H-bridge motor driver module',
    group: 'switching',
    symbol: 'driver',
    unlockLevel: 7,
    what: 'A board of switches that lets a microcontroller control a motor’s big current.',
    does: 'Four MOSFETs in an H shape connect the motor to the battery either way round. EN (with PWM) sets the speed and DIR sets the direction.',
    why: 'A pin can supply 20 mA; a motor wants an amp. The driver takes orders from the pin and power from the battery.',
    where: ['Every wheeled robot', 'Drones (as speed controllers)', '3D printers'],
    hotspots: [
      { id: 'chip', label: 'H-bridge chip', detail: 'Four MOSFET switches, plus logic that makes the dangerous combinations (shoot-through) impossible.', position: [0, 0.35, 0] },
      { id: 'terminals', label: 'Screw terminals', detail: 'Battery in (VM and GND), motor out (A and B). Thick wires go here.', position: [0.72, 0.5, 0] },
      { id: 'pins', label: 'Logic pins', detail: 'EN, DIR and GND go to the board. The shared GND is essential.', position: [-0.78, 0.45, 0] },
    ],
    tryIt: { label: 'Wire one up in Experiment 09', to: '/experiment/dc-motor' },
  },
  {
    id: 'li-ion',
    name: 'Li-ion battery pack',
    technical: '2S lithium-ion pack (7.4 V, 2600 mAh)',
    group: 'power',
    symbol: 'battery',
    unlockLevel: 8,
    what: 'Two rechargeable lithium cells wrapped together.',
    does: 'Two 3.7 V cells in series give 7.4 V. It stores far more energy for its weight than AA batteries.',
    why: 'Motors are hungry. A light, powerful, rechargeable pack keeps a robot running for hours.',
    where: ['Robots and drones', 'Laptops', 'Electric bikes'],
    hotspots: [
      { id: 'cells', label: 'Two cells in series', detail: '3.7 V + 3.7 V = 7.4 V, just like stacking AA cells in Level 1.', position: [0, 0.75, 0.4] },
      { id: 'label', label: 'Capacity', detail: '2600 mAh: in a perfect world, 2.6 A for an hour. Your power budget decides if that’s enough.', position: [0, 0.75, -0.2] },
      { id: 'leads', label: 'Red and black leads', detail: 'Red +, black −. A fuse belongs in the red lead, close to the pack. Never short these.', position: [1.6, 0.1, 0] },
    ],
    tryIt: { label: 'Plan a power budget', to: '/lesson/power-budget' },
  },
  {
    id: 'buck',
    name: 'Switching regulator',
    technical: 'Buck (step-down) converter module',
    group: 'power',
    symbol: 'regulator',
    unlockLevel: 8,
    what: 'A small board that turns a higher voltage into a steady lower one, without wasting much.',
    does: 'It switches the input on and off very fast and smooths the result with an inductor and capacitors. About 90% of the power gets through.',
    why: 'A linear regulator dropping 7.4 V to 5 V wastes a third of the energy as heat. A buck converter keeps the battery going longer and stays cool.',
    where: ['Robot power boards', 'USB chargers', 'Inside every laptop'],
    hotspots: [
      { id: 'inductor', label: 'Inductor', detail: 'A coil that stores energy in a magnetic field between switching pulses, smoothing out the flow.', position: [-0.15, 0.55, 0] },
      { id: 'caps', label: 'Capacitors', detail: 'Small tanks on the input and output that steady the voltage.', position: [-0.65, 0.65, 0.15] },
      { id: 'trim', label: 'Adjuster', detail: 'Some modules have a tiny potentiometer to set the output voltage. Turn it with a multimeter attached.', position: [0.75, 0.35, -0.3] },
    ],
    tryIt: { label: 'Compare regulators', to: '/lesson/regulators' },
  },
]

export const CATALOG_BY_ID = Object.fromEntries(CATALOG.map((c) => [c.id, c])) as Record<string, CatalogComponent>
