import type { CatalogComponent } from './types'

// Coordinates for hotspots match the procedural models in src/three/models.tsx:
// bodies sit around y = 0…1.5, legs point down to y ≈ −1.

export const CATALOG: CatalogComponent[] = [
  {
    id: 'battery',
    name: 'Battery',
    technical: 'Battery (9 V, 6LR61)',
    group: 'power',
    symbol: 'battery',
    unlockLevel: 1,
    what: 'A small box of chemicals that creates a steady push of electricity.',
    does: 'It keeps a fixed voltage between its + and − terminals, pushing current round any loop connected to them.',
    why: 'Without a source of push, nothing in a circuit moves. Every robot needs a power source.',
    where: ['Smoke alarms', 'Remote controls', 'Every mobile robot (usually a rechargeable pack)'],
    analogy: { text: 'A water pump that keeps the pressure up.', limit: 'A pump moves water from one place to another. A battery moves electrons round a loop, and they all come back.' },
    hotspots: [
      { id: 'pos', label: '+ terminal', detail: 'The small round snap. Conventional current flows out of here.', position: [-0.25, 1.95, 0] },
      { id: 'neg', label: '− terminal', detail: 'The larger hexagonal snap. Current returns here. We usually call this point ground (0 V).', position: [0.25, 1.95, 0] },
      { id: 'body', label: 'Six cells inside', detail: 'A 9 V battery is really six tiny 1.5 V cells connected in series: 6 × 1.5 = 9 V.', position: [0.52, 0.9, 0.32] },
    ],
    tryIt: { label: 'Stack cells in the battery lesson', to: '/lesson/batteries' },
  },
  {
    id: 'resistor',
    name: 'Resistor',
    technical: 'Resistor (through-hole, ¼ W)',
    group: 'passive',
    symbol: 'resistor',
    unlockLevel: 2,
    what: 'A small part that makes it harder for electricity to flow.',
    does: 'It limits how much current flows. Higher resistance (more ohms) means less current.',
    why: 'Lots of parts, LEDs especially, would draw too much current and destroy themselves. A resistor sets a safe amount.',
    where: ['Next to almost every LED', 'Setting signal levels for microcontrollers', 'Sensor circuits'],
    analogy: { text: 'A narrow section in a pipe.', limit: 'A narrow pipe doesn’t heat up, but a resistor turns the energy it blocks into heat.' },
    hotspots: [
      { id: 'bands', label: 'Colour bands', detail: 'The stripes encode its value. Yellow-violet-brown means 4, 7, plus one zero = 470 Ω.', position: [-0.3, 0.7, 0.25] },
      { id: 'body', label: 'Body', detail: 'Inside is a thin film of carbon or metal. Making the film longer or thinner increases the resistance.', position: [0.2, 0.7, 0.3] },
      { id: 'leads', label: 'Legs', detail: 'A resistor has no direction, so you can plug it in either way round.', position: [1.15, -0.5, 0] },
    ],
    tryIt: { label: 'Change resistors in Experiment 02', to: '/experiment/change-the-resistor' },
  },
  {
    id: 'led',
    name: 'LED',
    technical: 'Light-emitting diode (5 mm)',
    group: 'semiconductor',
    symbol: 'led',
    unlockLevel: 2,
    what: 'A tiny light that only lets current flow one way.',
    does: 'It glows when current flows from its long leg (+) to its short leg (−). Backwards, it stays dark.',
    why: 'Status lights, displays, and the “hello world” of electronics. It’s also a great way to see that current is flowing.',
    where: ['Power indicators', 'Screens and TVs', 'Robot status lights'],
    hotspots: [
      { id: 'anode', label: 'Long leg = + (anode)', detail: 'Connect this towards the battery’s +.', position: [-0.25, -1.15, 0] },
      { id: 'cathode', label: 'Short leg = − (cathode)', detail: 'Connect this towards the battery’s −.', position: [0.25, -0.75, 0] },
      { id: 'flat', label: 'Flat edge', detail: 'The rim is flattened on the − side. It’s handy when the legs have been cut to the same length.', position: [0.62, 0.08, 0] },
      { id: 'die', label: 'The chip (die)', detail: 'A speck of semiconductor that gives off light when current crosses it. The plastic dome works as a lens.', position: [0, 0.75, 0] },
    ],
    tryIt: { label: 'Light (and break) one in Experiment 01', to: '/experiment/light-an-led' },
  },
  {
    id: 'switch',
    name: 'Switch',
    technical: 'Toggle switch (SPST)',
    group: 'switching',
    symbol: 'switch',
    unlockLevel: 2,
    what: 'A lever that opens or closes a gap in the circuit.',
    does: 'Closed: the loop is complete and current flows. Open: there is a gap and nothing flows.',
    why: 'Turning things on and off by hand: power switches, mode selectors, safety cut-offs.',
    where: ['Robot power switches', 'Light switches', 'Torches'],
    hotspots: [
      { id: 'lever', label: 'Lever', detail: 'Flip it and a metal contact inside moves to touch, or let go of, the other contact.', position: [0.2, 1.4, 0] },
      { id: 'pins', label: 'Two pins', detail: 'SPST means single-pole single-throw: one circuit, one on/off position.', position: [0.3, -0.7, 0] },
    ],
  },
  {
    id: 'button',
    name: 'Push button',
    technical: 'Tactile switch (momentary)',
    group: 'switching',
    symbol: 'button',
    unlockLevel: 2,
    what: 'A switch that’s only on while you hold it down.',
    does: 'Pressing it closes the gap, and letting go opens it again (“momentary”).',
    why: 'It’s the simplest way for a person to give a robot an input, like Start, Reset or Mode.',
    where: ['Keyboards', 'Reset buttons', 'Microcontroller inputs'],
    hotspots: [
      { id: 'cap', label: 'Button cap', detail: 'Pushing it bends a tiny metal dome inside, which bridges the two contacts.', position: [0, 0.75, 0] },
      { id: 'legs', label: 'Four legs, two pairs', detail: 'The legs on opposite sides are permanently connected. The button connects one pair to the other.', position: [0.45, -0.4, 0.45] },
    ],
    tryIt: { label: 'Build a button-controlled LED in Experiment 03', to: '/experiment/button-led' },
  },
  {
    id: 'capacitor',
    name: 'Capacitor',
    technical: 'Electrolytic capacitor',
    group: 'passive',
    symbol: 'capacitor',
    unlockLevel: 2,
    what: 'A tiny, very fast energy storage tank.',
    does: 'It soaks up electrical charge and gives it back quickly, smoothing out sudden dips and spikes in voltage.',
    why: 'Motors and microcontrollers make the supply voltage wobble. Capacitors near them steady it so nothing resets at random.',
    where: ['Next to every chip on a board', 'Power supplies', 'Motor drivers'],
    analogy: { text: 'A small water tower that tops up the pressure when demand suddenly jumps.', limit: 'It holds very little energy compared with a battery, only enough for split-second gaps.' },
    hotspots: [
      { id: 'stripe', label: 'Minus stripe', detail: 'This type has a direction. The stripe marks the − leg, and fitting it backwards can make it fail, sometimes with a pop.', position: [0.5, 0.8, 0] },
      { id: 'vent', label: 'Safety vent', detail: 'The scored top lets gas escape safely if it’s abused, instead of bursting.', position: [0, 1.45, 0] },
      { id: 'legs', label: 'Long = +, short = −', detail: 'Same rule as an LED.', position: [-0.2, -0.9, 0] },
    ],
  },
  {
    id: 'diode',
    name: 'Diode',
    technical: 'Rectifier diode (1N4007)',
    group: 'semiconductor',
    symbol: 'diode',
    unlockLevel: 2,
    what: 'A one-way door for electricity.',
    does: 'Current can flow in the direction of the arrow on its symbol, but almost none flows the other way.',
    why: 'It protects circuits from batteries plugged in backwards, and stops motors kicking voltage back into your electronics.',
    where: ['Reverse-polarity protection', 'Across relay coils and motors', 'Converting AC to DC'],
    hotspots: [
      { id: 'band', label: 'Silver band = − side', detail: 'The band marks the cathode, the end current flows out of.', position: [0.4, 0.65, 0.25] },
      { id: 'body', label: 'Body', detail: 'Inside is a silicon junction. It needs about 0.7 V before it starts to conduct.', position: [-0.2, 0.65, 0.25] },
    ],
  },
  {
    id: 'transistor',
    name: 'Transistor',
    technical: 'Bipolar junction transistor (NPN, 2N2222)',
    group: 'semiconductor',
    symbol: 'npn',
    unlockLevel: 2,
    what: 'An electronic switch, or a valve, controlled by a tiny current.',
    does: 'A small current into its middle leg (base) lets a much bigger current flow between the other two legs.',
    why: 'A microcontroller pin can only supply a few milliamps. A transistor lets that weak signal control something bigger.',
    where: ['Driving LEDs and buzzers from a microcontroller', 'Amplifiers', 'Billions of them inside every chip'],
    hotspots: [
      { id: 'flat', label: 'Flat face', detail: 'Hold the flat face towards you to read the pin order from the datasheet, often E-B-C.', position: [0, 0.5, 0.15] },
      { id: 'base', label: 'Base (control)', detail: 'The small control current goes in here.', position: [0, -0.7, 0] },
      { id: 'ce', label: 'Collector & emitter', detail: 'The big current flows between these two.', position: [0.3, -0.7, 0] },
    ],
  },
  {
    id: 'mosfet',
    name: 'MOSFET',
    technical: 'N-channel MOSFET (TO-220)',
    group: 'semiconductor',
    symbol: 'mosfet',
    unlockLevel: 2,
    what: 'An electronic switch you can turn on and off with a small electrical signal.',
    does: 'Put voltage on its gate and a path opens between drain and source that can carry amps of current, with almost no control current needed.',
    why: 'Switching motors, lights and heaters from a microcontroller. It’s the workhorse of robot motor drivers.',
    where: ['Motor drivers', 'Drone speed controllers', 'Power supplies'],
    analogy: { text: 'A tap: a light twist on the handle (the gate) controls a big flow of water.', limit: 'A tap barely heats up. A MOSFET wastes a little power as heat, which is why it has a metal tab for a heatsink.' },
    hotspots: [
      { id: 'gate', label: 'Gate (G)', detail: 'The control leg. Voltage here, not current, opens the switch.', position: [-0.35, -0.7, 0] },
      { id: 'drain', label: 'Drain (D)', detail: 'The load (e.g. a motor) usually connects here.', position: [0, -0.7, 0] },
      { id: 'tab', label: 'Metal tab', detail: 'Bolt a heatsink here to carry away heat. It’s electrically connected to the drain.', position: [0, 1.35, -0.2] },
    ],
  },
  {
    id: 'relay',
    name: 'Relay',
    technical: 'Electromechanical relay (5 V coil)',
    group: 'switching',
    symbol: 'relay',
    unlockLevel: 2,
    what: 'A switch flipped by a small electromagnet.',
    does: 'Powering the coil makes it magnetic, which pulls a metal arm and closes a completely separate circuit. You can hear it click.',
    why: 'It lets a low-voltage circuit safely control a totally separate, even high-voltage, circuit.',
    where: ['Home automation', 'Car electronics', 'Industrial machines'],
    hotspots: [
      { id: 'coil', label: 'Coil (inside)', detail: 'A coil of thin wire. Current through it makes a magnet.', position: [-0.35, 0.95, 0.42] },
      { id: 'contacts', label: 'Switch contacts (inside)', detail: 'Pulled closed by the magnet. This side is electrically separate from the coil.', position: [0.35, 0.95, 0.42] },
    ],
  },
  {
    id: 'connector',
    name: 'Connector',
    technical: 'Screw terminal block (2-pin)',
    group: 'connection',
    symbol: 'connector',
    unlockLevel: 2,
    what: 'A way to plug or screw wires onto a board so they can be removed later.',
    does: 'Clamps a wire firmly against a metal contact that’s soldered to the board.',
    why: 'Batteries, motors and sensors need to be attached and detached. Connectors make that possible without soldering.',
    where: ['Battery inputs', 'Motor outputs on drivers', 'Every robot wiring harness'],
    hotspots: [
      { id: 'screw', label: 'Clamp screw', detail: 'Tighten it to squeeze the wire against the contact.', position: [-0.3, 0.95, 0] },
      { id: 'entry', label: 'Wire entry', detail: 'Strip about 5 mm of insulation and push the bare wire in here.', position: [-0.3, 0.4, 0.45] },
    ],
  },
  {
    id: 'fuse',
    name: 'Fuse',
    technical: 'Glass cartridge fuse',
    group: 'protection',
    symbol: 'fuse',
    unlockLevel: 2,
    what: 'A thin wire designed to melt on purpose.',
    does: 'If too much current flows, for example in a short circuit, the wire melts and breaks the loop before anything else gets damaged.',
    why: 'Robot batteries can deliver enough current to start a fire. A fuse is cheap insurance.',
    where: ['Battery packs', 'Cars', 'Power inputs on robot boards'],
    hotspots: [
      { id: 'element', label: 'Fuse wire', detail: 'Sized to melt at a chosen current, for example 2 A.', position: [0, 0.65, 0.2] },
      { id: 'caps', label: 'Metal end caps', detail: 'They clip into a fuse holder, so a blown fuse is easy to replace.', position: [0.7, 0.65, 0] },
    ],
  },
  {
    id: 'regulator',
    name: 'Voltage regulator',
    technical: 'Linear regulator (7805)',
    group: 'power',
    symbol: 'regulator',
    unlockLevel: 2,
    what: 'A part that turns a wobbly or too-high voltage into a steady one.',
    does: 'Feed it anything from about 7 V to 20 V and it outputs a steady 5 V.',
    why: 'Motors want battery voltage, but microcontrollers need exactly 5 V or 3.3 V. A regulator gives the brain a clean supply.',
    where: ['Arduino boards', 'Robot power systems', 'USB gadgets'],
    hotspots: [
      { id: 'in', label: 'Input', detail: 'Higher, unregulated voltage goes in here (e.g. 9 V battery).', position: [-0.35, -0.7, 0] },
      { id: 'gnd', label: 'Ground', detail: 'The shared 0 V reference.', position: [0, -0.7, 0] },
      { id: 'out', label: 'Output', detail: 'A steady 5 V comes out. The extra voltage is burned off as heat.', position: [0.35, -0.7, 0] },
    ],
  },
]

export const CATALOG_BY_ID = Object.fromEntries(CATALOG.map((c) => [c.id, c])) as Record<string, CatalogComponent>
