import type { Hub, HubId } from './types'

export const HUBS: Hub[] = [
  {
    id: 'electricity',
    name: 'Electricity Lab',
    icon: '⚡',
    color: '#fbbf24',
    tagline: 'What electricity is, and what makes it move.',
    unlockLevel: 1,
    chainLabel: 'Electricity',
    topics: ['Voltage', 'Current', 'Resistance', 'Power', 'Ground', 'AC vs DC', 'Batteries', 'Safety'],
    status: 'open',
  },
  {
    id: 'components',
    name: 'Components Lab',
    icon: '🔧',
    color: '#38bdf8',
    tagline: 'Pick up every part, turn it over, find out what it does.',
    unlockLevel: 2,
    chainLabel: 'Components',
    topics: ['Resistors', 'Capacitors', 'Diodes', 'LEDs', 'Transistors', 'MOSFETs', 'Relays', 'Connectors', 'Fuses', 'Regulators'],
    status: 'open',
  },
  {
    id: 'circuits',
    name: 'Circuit Lab',
    icon: '🔌',
    color: '#34d399',
    tagline: 'Wire parts together and watch what happens.',
    unlockLevel: 3,
    chainLabel: 'Circuits',
    topics: ['Complete loops', 'Series', 'Current limiting', 'Switches', 'Debugging'],
    status: 'open',
  },
  {
    id: 'microcontrollers',
    name: 'Microcontroller Lab',
    icon: '🧠',
    color: '#a78bfa',
    tagline: 'A tiny computer that lets software control hardware.',
    unlockLevel: 4,
    chainLabel: 'Microcontroller',
    topics: ['Digital signals', 'Analog signals', 'Voltage dividers', 'GPIO', 'PWM', 'ADC', 'Basic code'],
    status: 'open',
  },
  {
    id: 'robotics',
    name: 'Robotics Lab',
    icon: '🤖',
    color: '#f472b6',
    tagline: 'Sensors, motors, drivers and power. How robots sense and move.',
    unlockLevel: 6,
    chainLabel: 'Sensors · Motors · Power',
    topics: ['Sensors', 'DC motors', 'Servos', 'Steppers', 'Motor drivers', 'Encoders', 'Power systems', 'Robot control'],
    status: 'open',
  },
  {
    id: 'pcb',
    name: 'PCB Lab',
    icon: '🟩',
    color: '#4ade80',
    tagline: 'Turn a messy wire circuit into a real circuit board.',
    unlockLevel: 10,
    chainLabel: 'PCB',
    topics: ['Schematics', 'Symbols', 'Nets', 'Footprints', 'Layers', 'Traces', 'Vias', 'Ground planes', 'Design rules', 'Manufacturing'],
    status: 'preview',
  },
  {
    id: 'projects',
    name: 'Project Bay',
    icon: '🛠️',
    color: '#fb923c',
    tagline: 'Design the electronics for your own robot, from idea to board.',
    unlockLevel: 12,
    chainLabel: 'Robot',
    topics: ['Requirements', 'Block diagram', 'Component selection', 'Schematic', 'PCB', '3D board', 'Complete robot'],
    status: 'preview',
  },
]

export const HUB_BY_ID = Object.fromEntries(HUBS.map((h) => [h.id, h])) as Record<HubId, Hub>
