import type { CapstoneStage, Level } from './types'

export const LEVELS: Level[] = [
  {
    n: 1,
    title: 'What is Electricity?',
    tagline: 'Push, flow, and the loop that makes it all work.',
    hubId: 'electricity',
    ability: 'You can explain what voltage, current and resistance are, and predict current with Ohm’s law.',
    topics: ['Loops', 'Voltage', 'Current', 'Resistance', 'Power', 'Ground', 'AC vs DC', 'Batteries', 'Safety'],
    status: 'ready',
    items: [
      { type: 'lesson', id: 'loop' },
      { type: 'lesson', id: 'voltage' },
      { type: 'lesson', id: 'current-resistance' },
      { type: 'lesson', id: 'power' },
      { type: 'lesson', id: 'ground' },
      { type: 'lesson', id: 'ac-dc' },
      { type: 'lesson', id: 'batteries' },
      { type: 'lesson', id: 'safety' },
    ],
  },
  {
    n: 2,
    title: 'Meet the Components',
    tagline: 'Pick up every part and find out what it’s for.',
    hubId: 'components',
    ability: 'You can recognise common parts, read a resistor, and tell which way an LED goes.',
    topics: ['Resistors', 'LEDs', 'Capacitors', 'Diodes', 'Switches', 'Transistors', 'MOSFETs'],
    status: 'ready',
    items: [
      { type: 'lesson', id: 'led-legs' },
      { type: 'lesson', id: 'resistor-colors' },
      { type: 'collect', id: 'starter-kit', title: 'Inspect the starter kit', componentIds: ['resistor', 'led', 'capacitor', 'diode', 'switch'] },
    ],
  },
  {
    n: 3,
    title: 'Build Your First Circuit',
    tagline: 'Wire it, break it, fix it, understand it.',
    hubId: 'circuits',
    ability: 'You can build and debug a working LED circuit and choose a safe resistor value.',
    topics: ['Complete loops', 'Current limiting', 'Series circuits', 'Switches', 'Debugging'],
    status: 'ready',
    items: [
      { type: 'experiment', id: 'light-an-led' },
      { type: 'experiment', id: 'change-the-resistor' },
      { type: 'experiment', id: 'button-led' },
    ],
  },
  {
    n: 4,
    title: 'Understand Signals',
    tagline: 'On/off vs. everything in between.',
    hubId: 'microcontrollers',
    ability: 'You can tell digital from analog signals, split a voltage with resistors, and read a knob with a microcontroller.',
    topics: ['Digital signals', 'Analog signals', 'Logic thresholds', 'Voltage dividers', 'Potentiometers', 'ADC'],
    status: 'ready',
    items: [
      { type: 'lesson', id: 'signals' },
      { type: 'lesson', id: 'voltage-divider' },
      { type: 'lesson', id: 'potentiometer' },
      { type: 'experiment', id: 'read-pot' },
    ],
  },
  {
    n: 5,
    title: 'Meet the Microcontroller',
    tagline: 'Software that switches hardware.',
    hubId: 'microcontrollers',
    ability: 'You can make a microcontroller read a button and drive an LED with code, and dim it with PWM.',
    topics: ['GPIO', 'Digital input/output', 'Basic programming', 'Pull-down resistors', 'PWM'],
    status: 'ready',
    items: [
      { type: 'lesson', id: 'meet-mcu' },
      { type: 'lesson', id: 'first-code' },
      { type: 'lesson', id: 'pwm' },
      { type: 'experiment', id: 'button-code' },
      { type: 'experiment', id: 'knob-dimmer' },
    ],
  },
  {
    n: 6,
    title: 'Sensors & Inputs',
    tagline: 'How robots perceive the world.',
    hubId: 'robotics',
    ability: 'You can connect sensors, read light, distance and temperature, and turn their signals into real-world numbers.',
    topics: ['Analog sensors', 'Light (LDR)', 'Distance (ultrasonic)', 'Temperature', 'Datasheets & calibration', 'Communication (I²C, UART)'],
    status: 'ready',
    items: [
      { type: 'lesson', id: 'sensors' },
      { type: 'lesson', id: 'light-sensor' },
      { type: 'lesson', id: 'ultrasonic' },
      { type: 'lesson', id: 'talking-chips' },
      { type: 'experiment', id: 'read-temp' },
    ],
  },
  {
    n: 7,
    title: 'Motors & Outputs',
    tagline: 'How robots move.',
    hubId: 'robotics',
    ability: 'You can point a servo, drive a DC motor through an H-bridge driver, and measure distance with an encoder.',
    topics: ['DC motors', 'Stall current', 'H-bridges', 'Motor drivers', 'Servos', 'Steppers', 'Encoders'],
    status: 'ready',
    items: [
      { type: 'lesson', id: 'dc-motors' },
      { type: 'lesson', id: 'h-bridge' },
      { type: 'lesson', id: 'servos-steppers' },
      { type: 'experiment', id: 'servo' },
      { type: 'experiment', id: 'dc-motor' },
      { type: 'experiment', id: 'encoder' },
    ],
  },
  {
    n: 8,
    title: 'Power Systems',
    tagline: 'Feeding hungry motors and a picky brain.',
    hubId: 'robotics',
    ability: 'You can size a battery, regulate voltage and protect your circuit.',
    topics: ['Power budgets', 'Battery choice', 'Linear & switching regulators', 'Fuses', 'Reverse-polarity protection'],
    status: 'ready',
    items: [
      { type: 'lesson', id: 'power-budget' },
      { type: 'lesson', id: 'regulators' },
      { type: 'lesson', id: 'protection' },
      { type: 'collect', id: 'power-kit', title: 'Inspect the power kit', componentIds: ['li-ion', 'fuse', 'diode', 'regulator', 'buck'] },
    ],
  },
  {
    n: 9,
    title: 'Build a Robot Brain',
    tagline: 'Sensor → decision → motor.',
    hubId: 'robotics',
    ability: 'You can combine sensors, a microcontroller, a driver and power into one working system.',
    topics: ['Block diagrams', 'Control loops', 'Proportional control', 'Obstacle avoidance', 'Edge cases'],
    status: 'ready',
    items: [
      { type: 'lesson', id: 'block-diagrams' },
      { type: 'lesson', id: 'control-loops' },
      { type: 'experiment', id: 'obstacle' },
    ],
  },
  {
    n: 10,
    title: 'Understand Schematics',
    tagline: 'The language every circuit is written in.',
    hubId: 'pcb',
    ability: 'You can read and draw a schematic for your own circuit.',
    topics: ['Symbols', 'Nets', 'Labels', 'Power symbols', 'Reading datasheets'],
    status: 'planned',
    items: [],
  },
  {
    n: 11,
    title: 'Design a PCB',
    tagline: 'From wires to copper.',
    hubId: 'pcb',
    ability: 'You can lay out and route a two-layer PCB ready for manufacturing.',
    topics: ['Footprints', 'Layers', 'Traces', 'Vias', 'Ground planes', 'Design rules', 'Gerbers'],
    status: 'planned',
    items: [],
  },
  {
    n: 12,
    title: 'Build the Final System',
    tagline: 'Your robot, your electronics.',
    hubId: 'projects',
    ability: 'You can design the complete electronics and PCB for your own small robot.',
    topics: ['Requirements', 'Block diagram', 'Component selection', 'Schematic', 'PCB', 'Integration'],
    status: 'planned',
    items: [{ type: 'experiment', id: 'mini-robot' }],
  },
]

export const LEVEL_BY_N = Object.fromEntries(LEVELS.map((l) => [l.n, l])) as Record<number, Level>

export const CAPSTONE: CapstoneStage[] = [
  { n: 1, title: 'Requirements', question: 'What should the robot do?', description: 'Write down what your robot must sense, how it moves, how long it runs and how big it can be. Every later choice comes from this list.', learnedIn: [9] },
  { n: 2, title: 'Block diagram', question: 'What are the big pieces and how do they connect?', description: 'Battery → power system → microcontroller → sensors and motor driver → motors. Draw boxes and arrows before you choose a single part.', learnedIn: [9] },
  { n: 3, title: 'Component selection', question: 'Which exact parts?', description: 'Choose a microcontroller, sensors, motors, a driver that can handle the motor current, a battery, a regulator, connectors and protection.', learnedIn: [2, 5, 6, 7, 8] },
  { n: 4, title: 'Schematic', question: 'How is every pin wired?', description: 'Turn the block diagram into a precise circuit diagram. It’s the source of truth for the whole board.', learnedIn: [10] },
  { n: 5, title: 'PCB layout', question: 'Where does everything go physically?', description: 'Place footprints, route copper traces, add a ground plane and check the design rules.', learnedIn: [11] },
  { n: 6, title: '3D board check', question: 'Will it fit and can it be built?', description: 'Inspect the board in 3D. Check that connectors face outwards, mounting holes line up, and nothing collides.', learnedIn: [11] },
  { n: 7, title: 'Complete robot', question: 'Does the whole system work?', description: 'Drop your board into the robot chassis and watch it sense, decide and move.', learnedIn: [12] },
]
