import type { Lesson } from '../types'

export const ELECTRICITY_LESSONS: Lesson[] = [
  {
    id: 'loop',
    levelN: 1,
    hubId: 'electricity',
    title: 'Electricity needs a loop',
    summary: 'What is actually moving inside a wire, and why it only moves around a complete path.',
    minutes: 4,
    xp: 40,
    steps: [
      {
        kind: 'talk',
        title: 'Tiny movers inside the wire',
        body: [
          'Metal wire is packed with tiny particles called electrons. In metals like copper, some of them aren’t stuck to anything, so they can drift from atom to atom.',
          'Electricity is just a huge number of those electrons moving together in the same direction.',
          'The important bit is that the wire is already full of them. A battery doesn’t pour electrons in. It pushes the ones that are already there.',
        ],
        term: { name: 'Electron', plain: 'A tiny particle with a negative charge. Moving electrons are what we call electric current.' },
      },
      {
        kind: 'try',
        title: 'Close the loop',
        prompt: 'Here’s a battery, a light bulb and a switch. The switch is open, which leaves a gap. Click the switch to close it and watch the blue dots, which are electrons.',
        widget: 'flow-loop',
        widgetProps: { controls: [], voltage: 6, switchClosed: false },
        goal: { event: 'switch-closed', label: 'Close the switch' },
        reveal: 'As soon as the loop closes, electrons all the way round the wire start moving together, so the bulb lights straight away. The electrons from the battery don’t have to “arrive” first.',
      },
      {
        kind: 'try',
        title: 'Now break it',
        prompt: 'Click the switch again to open the gap.',
        widget: 'flow-loop',
        widgetProps: { controls: [], voltage: 6, switchClosed: true },
        goal: { event: 'switch-opened', label: 'Open the switch' },
        reveal: 'One gap anywhere stops the flow everywhere, even in parts of the wire far away from the gap. That’s all a switch is: a gap you can open and close on purpose.',
      },
      {
        kind: 'talk',
        title: 'That loop has a name',
        body: [
          'A complete path that electricity can flow all the way round is called a circuit. The word comes from “circle”.',
          'Every working electronic thing you’ll ever build, whether it’s a torch, a phone or a robot, is made of circuits. If something doesn’t work, the first question is always: is the loop complete?',
        ],
        term: { name: 'Circuit', plain: 'A closed loop that electricity can flow around, from the battery, through parts, and back.' },
        analogy: {
          text: 'A circuit is like a bike chain. Push the pedal and every link moves at once. Break one link and the whole chain stops.',
          limit: 'A chain only works if it’s pulled tight. Electricity doesn’t need tension; it needs a voltage pushing it, which comes next.',
        },
      },
      {
        kind: 'check',
        title: 'Quick check',
        question: 'A bulb is connected to a battery in a loop. You cut the wire on the far side of the bulb, away from the battery. What happens?',
        options: [
          { text: 'The bulb stays on. The cut is after the bulb.', correct: false, feedback: 'It’s easy to think that, but the current has to come back to the battery. A gap anywhere in the loop stops the flow everywhere.' },
          { text: 'The bulb goes out.', correct: true, feedback: 'Yes. A broken loop means no flow anywhere, and it doesn’t matter where the gap is.' },
          { text: 'The bulb gets brighter.', correct: false, feedback: 'Not quite. With no complete path, nothing flows at all.' },
        ],
      },
    ],
  },
  {
    id: 'voltage',
    levelN: 1,
    hubId: 'electricity',
    title: 'Voltage: the push',
    summary: 'What a battery actually gives a circuit, and why more “volts” makes things brighter.',
    minutes: 4,
    xp: 40,
    steps: [
      {
        kind: 'talk',
        title: 'Something has to push',
        body: [
          'Electrons won’t move on their own. Something has to push them around the loop. A battery is a push-maker.',
          'How hard it pushes is measured in volts (V). An AA battery pushes with 1.5 V and a 9 V battery pushes six times harder.',
        ],
        term: { name: 'Voltage (V)', plain: 'How hard electricity is being pushed between two points.' },
        analogy: {
          text: 'Think of water pipes. Voltage is like water pressure: more pressure pushes more water through.',
          limit: 'Water pressure exists at a single point, but voltage is always a difference between two points. “The voltage at this wire” really means “compared to somewhere else” (we’ll fix that with ground soon).',
        },
      },
      {
        kind: 'try',
        title: 'Turn up the push',
        prompt: 'Drag the voltage slider up to 9 V or more. Watch the electron speed and the bulb.',
        widget: 'flow-loop',
        widgetProps: { controls: ['voltage'], voltage: 1.5, switchClosed: true },
        goal: { event: 'voltage-high', label: 'Reach 9 V or more' },
        reveal: 'More push means the electrons move faster, more current flows, and the bulb gets brighter. Same wire, same bulb. The only thing you changed was the push.',
      },
      {
        kind: 'try',
        title: 'Take the push away',
        prompt: 'Now slide it all the way down to 0 V.',
        widget: 'flow-loop',
        widgetProps: { controls: ['voltage'], voltage: 9, switchClosed: true },
        goal: { event: 'voltage-zero', label: 'Set 0 V' },
        reveal: 'The wire is still full of electrons. With nothing pushing them, they just sit there. A “dead” battery hasn’t run out of electrons; it has run out of push.',
      },
      {
        kind: 'check',
        title: 'Quick check',
        question: 'What does a 9 V battery have more of than a 1.5 V battery?',
        options: [
          { text: 'Electrons', correct: false, feedback: 'Not quite. The electrons are already in the wire. The battery provides the push.' },
          { text: 'Push (voltage)', correct: true, feedback: 'Exactly. 9 V pushes six times harder than 1.5 V.' },
          { text: 'Wire', correct: false, feedback: 'The wire is the same. What changes is how hard the battery pushes.' },
        ],
      },
    ],
  },
  {
    id: 'current-resistance',
    levelN: 1,
    hubId: 'electricity',
    title: 'Current and resistance',
    summary: 'How much flows, what slows it down, and the one rule that links push, flow and resistance.',
    minutes: 6,
    xp: 60,
    steps: [
      {
        kind: 'talk',
        title: 'How much is flowing?',
        body: [
          'Current is how much electricity flows past a point every second. It’s measured in amps (A).',
          'Small electronics use tiny currents, so we often use milliamps (mA): 1000 mA = 1 A. An LED is happy with about 20 mA.',
        ],
        term: { name: 'Current (A)', plain: 'How much electricity is flowing past a point each second.' },
        analogy: {
          text: 'If voltage is water pressure, current is how many litres per second flow through the pipe.',
          limit: 'Water can leak out of a pipe, but current can’t. Exactly as much current comes back into the battery as left it. Nothing gets “used up” along the way, only energy.',
        },
      },
      {
        kind: 'talk',
        title: 'Something that makes flow harder',
        body: [
          'Everything in a circuit resists the flow a little. A bulb resists quite a lot, and that’s why it heats up and glows.',
          'Resistance is measured in ohms (Ω). More ohms means it’s harder to flow, so less current gets through.',
        ],
        term: { name: 'Resistance (Ω)', plain: 'How hard it is for electricity to flow through something.' },
        analogy: {
          text: 'Resistance is like a narrow section of pipe: it restricts how much water gets through.',
          limit: 'A narrow pipe doesn’t get hot, but a resistor does. Resistance turns electrical energy into heat.',
        },
      },
      {
        kind: 'try',
        title: 'Challenge: hit 0.50 A',
        prompt: 'Use both sliders to make exactly 0.50 A flow. Keep an eye on the meter as you go.',
        widget: 'flow-loop',
        widgetProps: { controls: ['voltage', 'resistance'], voltage: 3, resistance: 12, switchClosed: true, targetCurrent: 0.5 },
        goal: { event: 'current-target', label: 'Make 0.50 A flow' },
        reveal: 'Did you spot the pattern? Double the push and you double the flow. Double the resistance and you halve the flow. Current = Voltage ÷ Resistance.',
      },
      {
        kind: 'talk',
        title: 'The rule you just discovered',
        body: [
          'That pattern is the most useful rule in electronics: Current = Voltage ÷ Resistance, or I = V ÷ R for short.',
          'Rearranged, it tells you anything from the other two. Want 0.02 A through something from a 9 V battery? You need about 9 ÷ 0.02 = 450 Ω. You’ll use exactly that to protect an LED in the Circuit Lab.',
        ],
        term: { name: 'Ohm’s law', plain: 'Current = Voltage ÷ Resistance. Push divided by difficulty gives you flow.' },
      },
      {
        kind: 'check',
        title: 'Quick check',
        question: 'A 9 V battery pushes current through 18 Ω. How much current flows?',
        options: [
          { text: '0.5 A', correct: true, feedback: 'Yes: 9 ÷ 18 = 0.5 A.' },
          { text: '2 A', correct: false, feedback: 'That’s 18 ÷ 9. It’s voltage divided by resistance, not the other way round.' },
          { text: '162 A', correct: false, feedback: 'That’s 9 × 18. Resistance reduces current, so we divide.' },
        ],
      },
    ],
  },
  {
    id: 'power',
    levelN: 1,
    hubId: 'electricity',
    title: 'Power: doing work',
    summary: 'Why some parts get hot, and how to work out how much energy a part is using.',
    minutes: 4,
    xp: 40,
    steps: [
      {
        kind: 'talk',
        title: 'Where does the energy go?',
        body: [
          'A battery stores energy. As current flows, that energy gets turned into something useful (light, movement, sound) and usually some heat too.',
          'Power is how fast that happens. It’s measured in watts (W). Power = Voltage × Current.',
        ],
        term: { name: 'Power (W)', plain: 'How quickly electrical energy is being turned into light, heat or motion.' },
      },
      {
        kind: 'try',
        title: 'Make it work harder',
        prompt: 'Get the bulb to use at least 5 W. Watch the resistor as you do it.',
        widget: 'flow-loop',
        widgetProps: { controls: ['voltage', 'resistance'], voltage: 3, resistance: 10, switchClosed: true, targetPower: 5 },
        goal: { event: 'power-target', label: 'Bulb at 5 W or more' },
        reveal: 'The resistor started glowing orange too. It turns its share of the energy into heat. Every part has a power rating, a limit on how much heat it can get rid of before it’s damaged.',
      },
      {
        kind: 'check',
        title: 'Quick check',
        question: 'A motor runs on 6 V and draws 2 A. How much power does it use?',
        options: [
          { text: '3 W', correct: false, feedback: 'That’s 6 ÷ 2. For power we multiply.' },
          { text: '12 W', correct: true, feedback: 'Right: 6 V × 2 A = 12 W.' },
          { text: '8 W', correct: false, feedback: 'That’s 6 + 2. Power = voltage × current.' },
        ],
      },
    ],
  },
  {
    id: 'ground',
    levelN: 1,
    hubId: 'electricity',
    title: 'Ground: the zero point',
    summary: 'Why every voltage you measure is really a comparison, and what “ground” means.',
    minutes: 4,
    xp: 40,
    steps: [
      {
        kind: 'talk',
        title: 'Compared to what?',
        body: [
          'Voltage is always a difference between two points, a bit like a height difference.',
          'To keep things simple, we pick one point in the circuit, usually the battery’s −, and call it 0 V. Every other voltage is then measured from there.',
        ],
        term: { name: 'Ground (GND)', plain: 'The point in a circuit we agree to call 0 V. Everything else is measured from it.' },
        analogy: {
          text: 'Ground is like sea level. Mountain heights are measured from sea level, and circuit voltages are measured from ground.',
          limit: 'In small battery circuits, “ground” has nothing to do with the earth outside. It’s just the name for our chosen 0 V point.',
        },
      },
      {
        kind: 'try',
        title: 'Take some measurements',
        prompt: 'The black probe is on ground. Click each point (A, B, C, D) with the red probe and read the voltage.',
        widget: 'ground-probe',
        goal: { event: 'probed-all', label: 'Measure all four points' },
        reveal: 'Voltage drops step by step as current passes through each part. It starts at the full battery voltage at the + side and reaches 0 V by the time it gets back to ground.',
      },
      {
        kind: 'check',
        title: 'Quick check',
        question: 'Your multimeter reads 5 V at a point. What does that really mean?',
        options: [
          { text: 'The point is 5 V higher than ground.', correct: true, feedback: 'Exactly. Every reading is a comparison with the black probe, which is usually on ground.' },
          { text: '5 A is flowing there.', correct: false, feedback: 'Volts measure push, not flow. Flow is current, measured in amps.' },
          { text: 'The wire contains 5 volts of electrons.', correct: false, feedback: 'Voltage isn’t stored in a wire. It’s a difference in push between two points.' },
        ],
      },
    ],
  },
  {
    id: 'ac-dc',
    levelN: 1,
    hubId: 'electricity',
    title: 'AC vs DC',
    summary: 'The two kinds of electricity, and why your robot will use only one of them.',
    minutes: 3,
    xp: 30,
    steps: [
      {
        kind: 'talk',
        title: 'One way, or back and forth?',
        body: [
          'Batteries push electricity steadily in one direction. That’s DC (direct current).',
          'Wall sockets push it forwards, then backwards, 50 or 60 times every second. That’s AC (alternating current).',
        ],
        term: { name: 'DC / AC', plain: 'DC flows steadily one way. AC keeps flipping direction back and forth.' },
      },
      {
        kind: 'try',
        title: 'Watch both',
        prompt: 'Switch between DC and AC. Watch the electrons in the wire and the graph that tracks the voltage over time.',
        widget: 'ac-dc',
        goal: { event: 'compared', label: 'Try both DC and AC' },
        reveal: 'With AC the electrons mostly shuffle back and forth without getting anywhere, but they still deliver energy. Robots, microcontrollers and most electronics run on DC. Phone chargers convert the AC from the wall into DC.',
      },
      {
        kind: 'check',
        title: 'Quick check',
        question: 'Your robot runs from a battery pack. What kind of electricity does it use?',
        options: [
          { text: 'DC', correct: true, feedback: 'Yes. Batteries always give DC.' },
          { text: 'AC', correct: false, feedback: 'Batteries push in one direction only, so that’s DC.' },
        ],
      },
    ],
  },
  {
    id: 'batteries',
    levelN: 1,
    hubId: 'electricity',
    title: 'Batteries',
    summary: 'How cells stack up to give more push, and what “mAh” on the label means.',
    minutes: 4,
    xp: 40,
    steps: [
      {
        kind: 'talk',
        title: 'A battery is a stack of cells',
        body: [
          'Each cell uses chemistry to make a fixed push. An AA cell gives about 1.5 V and a lithium cell gives about 3.7 V.',
          'Connect cells end to end (+ to −) and their pushes add up. This is called connecting them in series.',
        ],
        term: { name: 'Series', plain: 'Connected one after another in a single line, so the same current flows through each.' },
      },
      {
        kind: 'try',
        title: 'Build a 6 V pack',
        prompt: 'Add AA cells to the holder and flip them around if you like. Build a pack that gives exactly 6 V.',
        widget: 'battery-stack',
        goal: { event: 'made-6v', label: 'Make 6 V' },
        reveal: 'Four cells × 1.5 V = 6 V. Did you try flipping one? A backwards cell pushes against the others, so it cancels out two cells’ worth of push.',
      },
      {
        kind: 'talk',
        title: 'Push vs. fuel',
        body: [
          'Voltage is how hard a battery pushes. Capacity is how long it can keep pushing. Capacity is printed as mAh (milliamp-hours).',
          'A 2000 mAh battery can supply 2000 mA for one hour, or 200 mA for ten hours. When you design a robot, motors draw a lot of current, so capacity decides how long it runs.',
        ],
        term: { name: 'Capacity (mAh)', plain: 'How much current a battery can supply, and for how long.' },
      },
      {
        kind: 'check',
        title: 'Quick check',
        question: 'Your robot draws 500 mA. Roughly how long will a 2000 mAh battery last?',
        options: [
          { text: 'About 4 hours', correct: true, feedback: 'Yes: 2000 ÷ 500 = 4 hours. Real life is a bit less, because batteries don’t like being drained completely.' },
          { text: 'About 30 minutes', correct: false, feedback: 'Try 2000 mAh ÷ 500 mA.' },
          { text: 'About 1000 hours', correct: false, feedback: 'That would be 2000 × 500. Divide capacity by current instead.' },
        ],
      },
    ],
  },
  {
    id: 'safety',
    levelN: 1,
    hubId: 'electricity',
    title: 'Staying safe',
    summary: 'What’s safe to touch, what isn’t, and the habits real engineers use.',
    minutes: 3,
    xp: 30,
    steps: [
      {
        kind: 'talk',
        title: 'Low voltage is your playground',
        body: [
          'Everything in this lab is low-voltage DC: batteries of 12 V or less. It can’t give you a shock you’d feel.',
          'The dangers you do need to know about are heat, fire and wall power. Batteries can push a lot of current into a short circuit, and lithium batteries can catch fire if they’re damaged or shorted.',
        ],
      },
      {
        kind: 'try',
        title: 'Safe or not?',
        prompt: 'Sort each situation. Is it safe, or should you stop?',
        widget: 'safety-sort',
        goal: { event: 'sorted', label: 'Sort all cards correctly' },
        reveal: 'Good habits: unplug power before changing wires, never short a battery, keep wall power out of your projects until you really know what you’re doing, and feel for heat. A hot part is telling you something is wrong.',
      },
    ],
  },
]
